import {
  Loader2,
  ChevronLeft,
  ChevronRight,
  Command,
  Menu,
  Moon,
  Sun,
  Check,
  ChevronsUpDown,
  Plus,
  X,
  BarChart3,
  Settings,
  QrCode,
  Pencil,
  GripVertical,
  List,
  Trash,
  Copy,
  Utensils,
  type LucideIcon,
} from 'lucide-react'

export type Icon = LucideIcon

export const Icons = {
  logo: Utensils,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  menu: Menu,
  moon: Moon,
  sun: Sun,
  check: Check,
  chevronsUpDown: ChevronsUpDown,
  add: Plus,
  chart: BarChart3,
  settings: Settings,
  qr: QrCode,
  edit: Pencil,
  grip: GripVertical,
  list: List,
  trash: Trash,
  copy: Copy,
} as const 